blank_issues_enabled: false
contact_links:
  - name: ❗️ All other issues | 其他问题
    url: https://discord.nuxtjs.org/
    about: |
      Please use our Discord server for other issues and asking questions.
